// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhWIW0QAjNtVLZmP2iWCOwRp_8vWJPBNQ',
    appId: '1:78016706706:web:4ba4efb3cfda856f074e4b',
    messagingSenderId: '78016706706',
    projectId: 'chat-fb-app-58655',
    authDomain: 'chat-fb-app-58655.firebaseapp.com',
    storageBucket: 'chat-fb-app-58655.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA33zHwtdVBATTECWyODytLbcEoMDkcBw',
    appId: '1:78016706706:android:c42c6f73205da76d074e4b',
    messagingSenderId: '78016706706',
    projectId: 'chat-fb-app-58655',
    storageBucket: 'chat-fb-app-58655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqBPSQ__CjGhBq3jDOet0xfgXuiYBS7o',
    appId: '1:78016706706:ios:63b99a1a5b2e5cf5074e4b',
    messagingSenderId: '78016706706',
    projectId: 'chat-fb-app-58655',
    storageBucket: 'chat-fb-app-58655.appspot.com',
    iosBundleId: 'com.example.flutterTextmsgFbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzqBPSQ__CjGhBq3jDOet0xfgXuiYBS7o',
    appId: '1:78016706706:ios:0aa7525d9ff5cb44074e4b',
    messagingSenderId: '78016706706',
    projectId: 'chat-fb-app-58655',
    storageBucket: 'chat-fb-app-58655.appspot.com',
    iosBundleId: 'com.example.flutterTextmsgFbApp.RunnerTests',
  );
}
